[workspace]
members = [
    "leaf",
    "leaf-bin",
    "leaf-mobile",
    "tun2socks-bin",
]
default-members = ["leaf-bin"]

[profile.release]
opt-level = 3
lto = true
# codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
